//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tactividadobra
    {
        public int idtactividadobra { get; set; }
        public string nombre { get; set; }
        public string actividadobra { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> idproductoproyecto { get; set; }
    }
}
