//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tafp
    {
        public tafp()
        {
            this.tcomisiones = new HashSet<tcomisiones>();
            this.tregimenpensionariotrabajador = new HashSet<tregimenpensionariotrabajador>();
        }
    
        public int idtafp { get; set; }
        public string nombre { get; set; }
        public string codigosunat { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<tcomisiones> tcomisiones { get; set; }
        public virtual ICollection<tregimenpensionariotrabajador> tregimenpensionariotrabajador { get; set; }
    }
}
