//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class taportaciones
    {
        public int idtaportaciones { get; set; }
        public Nullable<int> idDetallePLanilla { get; set; }
        public Nullable<int> idMaestroAportaciones { get; set; }
        public Nullable<decimal> monto { get; set; }
    }
}
