//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcomisiones
    {
        public int idtcomisiones { get; set; }
        public int idtafp { get; set; }
        public Nullable<System.DateTime> mes { get; set; }
        public Nullable<decimal> primaseguros { get; set; }
        public Nullable<decimal> aporteobligatorio { get; set; }
        public Nullable<decimal> remuneracionasegurable { get; set; }
        public Nullable<decimal> comisionflujo { get; set; }
        public Nullable<decimal> comisionmixta { get; set; }
    
        public virtual tafp tafp { get; set; }
    }
}
