//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcontrato
    {
        public int idtContrato { get; set; }
        public Nullable<int> idtTrabajador { get; set; }
        public Nullable<int> idtsunattipotrabajador { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> idtmeta { get; set; }
    }
}
