//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdetalletareo
    {
        public int idtdetalletareo { get; set; }
        public string categoria { get; set; }
        public string diastareo { get; set; }
        public Nullable<int> idttrabajador { get; set; }
        public Nullable<int> idttareo { get; set; }
    
        public virtual ttareo ttareo { get; set; }
        public virtual ttrabajador ttrabajador { get; set; }
    }
}
