//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tdetalleplanilla
    {
        public int idtdetalleplanilla { get; set; }
        public Nullable<decimal> sueldo { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<int> diaslaborados { get; set; }
        public Nullable<int> idtcargo { get; set; }
        public Nullable<int> idttrabajador { get; set; }
        public Nullable<int> idtplanilla { get; set; }
    
        public virtual tcargo tcargo { get; set; }
        public virtual tplanilla tplanilla { get; set; }
        public virtual ttrabajador ttrabajador { get; set; }
    }
}
