//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfuentefinanciamiento
    {
        public tfuentefinanciamiento()
        {
            this.tplanilla = new HashSet<tplanilla>();
        }
    
        public int idtfuentefinanciamiento { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<tplanilla> tplanilla { get; set; }
    }
}
