//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmaestroingresos
    {
        public int idtmaestroingresos { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> essalud_trabajador { get; set; }
        public Nullable<bool> essalud_cbssp { get; set; }
        public Nullable<bool> essalud_agrario { get; set; }
        public Nullable<bool> essalud_sctr { get; set; }
        public Nullable<bool> impuesto_extraord { get; set; }
        public Nullable<bool> derechos_sociales { get; set; }
        public Nullable<bool> senati { get; set; }
        public Nullable<bool> snp { get; set; }
        public Nullable<bool> spp { get; set; }
        public Nullable<bool> renta_5ta { get; set; }
        public Nullable<bool> essalud_pensionista { get; set; }
        public Nullable<bool> contrib_solidaria { get; set; }
        public string calculo { get; set; }
        public string abreviacion { get; set; }
        public string tipo { get; set; }
    }
}
