//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmaestroaportacionesempleador
    {
        public int idtmaestroaportacionesempleador { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string calculo { get; set; }
        public string abreviacion { get; set; }
    }
}
