//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tperiodotrabajador
    {
        public tperiodotrabajador()
        {
            this.tregimenpensionariotrabajador = new HashSet<tregimenpensionariotrabajador>();
            this.tregimensaludtrabajador = new HashSet<tregimensaludtrabajador>();
            this.tregimentrabajador = new HashSet<tregimentrabajador>();
        }
    
        public int idtperiodotrabajador { get; set; }
        public string fechainicio { get; set; }
        public string fechafin { get; set; }
        public Nullable<int> idtmotivofinperiodo { get; set; }
        public Nullable<int> idttrabajador { get; set; }
    
        public virtual tmotivofinperiodo tmotivofinperiodo { get; set; }
        public virtual ttrabajador ttrabajador { get; set; }
        public virtual ICollection<tregimenpensionariotrabajador> tregimenpensionariotrabajador { get; set; }
        public virtual ICollection<tregimensaludtrabajador> tregimensaludtrabajador { get; set; }
        public virtual ICollection<tregimentrabajador> tregimentrabajador { get; set; }
    }
}
