//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tplantillaplanilla
    {
        public int idtplantillaplanilla { get; set; }
        public string tipo { get; set; }
        public Nullable<int> codigo { get; set; }
        public Nullable<int> idtregimenlaboral { get; set; }
    
        public virtual tregimenlaboral tregimenlaboral { get; set; }
    }
}
