//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tplanilla
    {
        public tplanilla()
        {
            this.tdetalleplanilla = new HashSet<tdetalleplanilla>();
        }
    
        public int idtplanilla { get; set; }
        public string numero { get; set; }
        public string mes { get; set; }
        public string año { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idtmeta { get; set; }
        public Nullable<int> idtfuentefinanciamiento { get; set; }
        public Nullable<int> idtregimenlaboral { get; set; }
    
        public virtual ICollection<tdetalleplanilla> tdetalleplanilla { get; set; }
        public virtual tfuentefinanciamiento tfuentefinanciamiento { get; set; }
        public virtual tmeta tmeta { get; set; }
        public virtual tregimenlaboral tregimenlaboral { get; set; }
    }
}
