//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tprovincia
    {
        public tprovincia()
        {
            this.tdistrito = new HashSet<tdistrito>();
        }
    
        public int idtprovincia { get; set; }
        public Nullable<int> codigoDepartamento { get; set; }
        public string codigoUbigeo { get; set; }
        public string descripcion { get; set; }
    
        public virtual tdepartamento tdepartamento { get; set; }
        public virtual ICollection<tdistrito> tdistrito { get; set; }
    }
}
