//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tregimentrabajador
    {
        public int idtregimentrabajador { get; set; }
        public string condicion { get; set; }
        public Nullable<bool> servidorconfianza { get; set; }
        public string numerodocumento { get; set; }
        public string periodicidad { get; set; }
        public string tipopago { get; set; }
        public Nullable<decimal> montopago { get; set; }
        public string fechainicio { get; set; }
        public string fechafin { get; set; }
        public string ruc { get; set; }
        public Nullable<int> idtregimenlaboral { get; set; }
        public Nullable<int> idttipotrabajador { get; set; }
        public Nullable<int> idttipocontrato { get; set; }
        public Nullable<int> idtcategoriaocupacional { get; set; }
        public Nullable<int> idtocupacion { get; set; }
        public Nullable<int> idtcargo { get; set; }
        public Nullable<int> idtmeta { get; set; }
        public Nullable<int> idtperiodotrabajador { get; set; }
    
        public virtual tcargo tcargo { get; set; }
        public virtual tcategoriaocupacional tcategoriaocupacional { get; set; }
        public virtual tmeta tmeta { get; set; }
        public virtual tocupacion tocupacion { get; set; }
        public virtual tperiodotrabajador tperiodotrabajador { get; set; }
        public virtual tregimenlaboral tregimenlaboral { get; set; }
        public virtual tsunattipotrabajador tsunattipotrabajador { get; set; }
        public virtual ttipocontrato ttipocontrato { get; set; }
    }
}
