//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tregimensaludtrabajador
    {
        public int idtregimensaludtrabajador { get; set; }
        public string regimensalud { get; set; }
        public string fechainicio { get; set; }
        public string fechafin { get; set; }
        public string entidadprestadorasalud { get; set; }
        public Nullable<int> idtperiodotrabajador { get; set; }
    
        public virtual tperiodotrabajador tperiodotrabajador { get; set; }
    }
}
