//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tregimenlaboral
    {
        public tregimenlaboral()
        {
            this.tplanilla = new HashSet<tplanilla>();
            this.tplantillaplanilla = new HashSet<tplantillaplanilla>();
            this.tregimentrabajador = new HashSet<tregimentrabajador>();
        }
    
        public int idtregimenlaboral { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<tplanilla> tplanilla { get; set; }
        public virtual ICollection<tplantillaplanilla> tplantillaplanilla { get; set; }
        public virtual ICollection<tregimentrabajador> tregimentrabajador { get; set; }
    }
}
