//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttareo
    {
        public ttareo()
        {
            this.tdetalletareo = new HashSet<tdetalletareo>();
        }
    
        public int idttareo { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> idtmeta { get; set; }
    
        public virtual ICollection<tdetalletareo> tdetalletareo { get; set; }
        public virtual tmeta tmeta { get; set; }
    }
}
