//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttipovia
    {
        public ttipovia()
        {
            this.ttrabajador = new HashSet<ttrabajador>();
        }
    
        public int idttipovia { get; set; }
        public string codigoSunat { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<ttrabajador> ttrabajador { get; set; }
    }
}
