//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaUsuario.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvariables
    {
        public int idtvariables { get; set; }
        public string año { get; set; }
        public Nullable<int> sueldominimo { get; set; }
        public Nullable<int> UIT { get; set; }
    }
}
